
export const GET_CALL_STATE = 'get_call_state';
export const REQUEST_MAKE_AUDIO_CALL = 'REQUEST_MAKE_AUDIO_CALL';
export const REQUEST_MAKE_VIDEO_CALL = 'REQUEST_MAKE_VIDEO_CALL';
export const REQUEST_TAKE_AUDIO_CALL = 'REQUEST_TAKE_AUDIO_CALL';
export const REQUEST_TAKE_VIDEO_CALL = 'REQUEST_TAKE_VIDEO_CALL';
