import LocalizedStrings from 'react-native-localization';

export default strings = new LocalizedStrings({
    "en-US": {
        login: "SIGN IN",
        logout: "Logout",
        username: "E-mail address",
        password: "Password",
        contacts: "Contacts",
        conversations: "Conversations",
        bubbles: "Bubbles",
        search: "Search",
        myProfile: "My profile",
        audioCall: "AUDIO CALL",
        videoCall: "VIDEO CALL",
        close:"CLOSE",
        continue: "CONTINUE",
        loginFaild: 'Incorrect username or password',
        connectionProgress:"Connection is in progress",
        emptyCredentialsMsTitle: 'Configuration error',
        emptyCredentialsMsgBody: 'Login or password is missing',
        forgotPwd: 'FORGOT YOUR PASSWORD?',
        createAccountMsgNew: 'CREATE YOUR ACCOUNT',
        alreadyHaveAccount: 'Already have an account ?'
    },
    en: {
        login: "SIGN IN",
        logout: "Logout",
        username: "E-mail address",
        password: "Password",
        contacts: "Contacts",
        conversations: "Conversations",
        bubbles: "Bubbles",
        search: "Search",
        myProfile: "My profile",
        audioCall: "AUDIO CALL",
        videoCall: "VIDEO CALL",
        close:"CLOSE",
        continue: "CONTINUE",
        loginFaild: 'Incorrect username or password',
        connectionProgress:"Connection is in progress",
        emptyCredentialsMsTitle: 'Configuration error',
        emptyCredentialsMsgBody: 'Login or password is missing',
        forgotPwd: 'FORGOT YOUR PASSWORD?',
        createAccountMsgNew: 'CREATE YOUR ACCOUNT',
        alreadyHaveAccount: 'Already have an account ?'
    },
    ar: {
        login: "تسجيل الدخول",
        logout: "تسجيل الخروج",
        username: "البريدالالكتروني",
        password: "كلمه المرور",
        contacts: "جهات الاتصال",
        conversations: "محادثاتي",
        bubbles: "الفقاعات",
        search: "بحث",
        myProfile: "ملف تعريفي",
        audioCall: "مكالمة صوتية",
        videoCall: "مكالمة فيديو",
        close:"اغلاق",
        continue: "استمرار",
        loginFaild: 'اسم المستخدم أو كلمة المرور غير صحيحة',
        connectionProgress:"جاري الأتصال",
        emptyCredentialsMsTitle: 'خطأ في الاعدادات',
        emptyCredentialsMsgBody: 'تسجيل الدخول أو كلمة المرور مفقودة',
        forgotPwd: 'هل نسيت كلمة المرور؟',
        createAccountMsgNew: 'أنشئ حسابك ',
        alreadyHaveAccount: 'لديك بالفعل حساب؟'

    }
});